services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    volumes:
      - ./src:/project
      - /data/protein/CAMEO/mongodb:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin123
    ports:
      - 27017:27017
  
  gui:
    build:
      context: ./gui
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    ports:
      - "80:4173"
    volumes:
      - ./gui:/app
    command: >
      bash -c "yrm use taobao
      && yarn
      && yarn build
      && yarn preview --host --port 4173"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./api:/app
      - /data:/data
      - ./lib:/app/lib
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis
      - HOST=0.0.0.0
      - PORT=8081
    command: uvicorn api:app --host 0.0.0.0 --port 8081
  
  worker_monitor:
    build:
      context: ./services/monitor
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - USER_NAME=${USER_NAME}
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis
    volumes:
      - ./services/monitor:/worker
      - /data:/data
      - ./lib:/worker/lib
    command: celery -A worker worker --loglevel=info -Q queue_monitor --concurrency=1

  worker_preprocess:
    build:
      context: ./services/preprocess
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - USER_NAME=${USER_NAME}
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis
    volumes:
      - ./services/preprocess:/worker
      - /data:/data
      - ./lib:/worker/lib
    command: celery -A worker worker --loglevel=info -Q queue_preprocess --concurrency=32
  
  worker_blast:
    build:
      context: ./services/blast
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - USER_NAME=${USER_NAME}
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis
    volumes:
      - ./services/blast:/worker
      - /data:/data
      - ./lib:/worker/lib
    command: celery -A worker worker --loglevel=info -Q queue_blast --concurrency=32

  worker_jackhmmer:
    build:
      context: ./services/jackhmmer
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - USER_NAME=${USER_NAME}
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis
    volumes:
      - ./services/jackhmmer:/worker
      - /data:/data
      - ./lib:/worker/lib
    command: celery -A worker worker --loglevel=info -Q queue_jackhmmer --concurrency=32

  worker_hhblits:
    build:
      context: ./services/hhblits
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - USER_NAME=${USER_NAME}
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis
    volumes:
      - ./services/hhblits:/worker
      - /data:/data
      - ./lib:/worker/lib
    command: celery -A worker worker --loglevel=info -Q queue_hhblits --concurrency=32

  worker_mmseqs:
    build:
      context: ./services/mmseqs
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - USER_NAME=${USER_NAME}
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis
    volumes:
      - ./services/mmseqs:/worker
      - /data:/data
      - ./lib:/worker/lib
    command: celery -A worker worker --loglevel=info -Q queue_mmseqs --concurrency=32

  worker_deepmsa:
    build:
      context: ./services/deepmsa
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - USER_NAME=${USER_NAME}
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis
    volumes:
      - ./services/deepmsa:/worker
      - /data:/data
      - ./lib:/worker/lib
    command: celery -A worker worker --loglevel=info -Q queue_deepmsa --concurrency=32

  worker_mergemsa:
    build:
      context: ./services/mergemsa
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - USER_NAME=${USER_NAME}
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis
    volumes:
      - ./services/mergemsa:/worker
      - /data:/data
      - ./lib:/worker/lib
    command: celery -A worker worker --loglevel=info -Q queue_mergemsa --concurrency=32

  worker_selectmsa:
    build:
      context: ./services/selectmsa
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - USER_NAME=${USER_NAME}
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis
    volumes:
      - ./services/selectmsa:/worker
      - /data:/data
      - ./lib:/worker/lib
    command: celery -A worker worker --loglevel=info -Q queue_selectmsa --concurrency=32

  worker_searchtpl:
    build:
      context: ./services/searchtpl
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - USER_NAME=${USER_NAME}
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # run docker in docker
      - ./services/searchtpl:/worker
      - /data:/data
      - ./lib:/worker/lib
    command: celery -A worker worker --loglevel=info -Q queue_searchtpl --concurrency=16

  worker_selecttpl:
    build:
      context: ./services/selecttpl
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - USER_NAME=${USER_NAME}
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis
    volumes:
      - ./services/selecttpl:/worker
      - /data:/data
      - ./lib:/worker/lib
    command: celery -A worker worker --loglevel=info -Q queue_selecttpl --concurrency=16

  worker_tplfeature:
    build:
      context: ./services/tplfeature
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - USER_NAME=${USER_NAME}
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # run docker in docker
      - ./services/tplfeature:/worker
      - /data:/data
      - ./lib:/worker/lib
    command: celery -A worker worker --loglevel=info -Q queue_tplfeature --concurrency=16

  worker_monostructure:
    build:
      context: ./services/monostructure
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - USER_NAME=${USER_NAME}
        - DOCKER_CLIENT_TIMEOUT=${DOCKER_CLIENT_TIMEOUT}
        - COMPOSE_HTTP_TIMEOUT=${COMPOSE_HTTP_TIMEOUT}
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # run docker in docker
      - ./services/monostructure:/worker
      - /data:/data
      - ./lib:/worker/lib
    command: celery -A worker worker --loglevel=info -Q queue_monostructure --concurrency=8

  worker_analysis:
    build:
      context: ./services/analysis
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - USER_NAME=${USER_NAME}
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis
    volumes:
      - ./services/analysis:/worker
      - /data:/data
      - ./lib:/worker/lib
    command: celery -A worker worker --loglevel=info -Q queue_analysis --concurrency=16

  worker_submit:
    build:
      context: ./services/submit
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - USER_ID=${UID}
        - GROUP_ID=${GID}
        - USER_NAME=${USER_NAME}
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis
    volumes:
      - ./services/submit:/worker
      - /data:/data
      - ./lib:/worker/lib
    command: celery -A worker worker --loglevel=info -Q queue_submit --concurrency=32

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
      
  redis:
    image: redis:latest

  # # Optionally, you can also include Flower for monitoring the Celery tasks
  # flower:
  #   image: mher/flower
  #   command: celery --broker=amqp://rabbitmq:5672 flower --port=5555
  #   ports:
  #     - "5556:5555"
  #   depends_on:
  #     - rabbitmq

networks:
  default:
    driver: bridge
