version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
    volumes:
      - ./api:/app
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc://
      - HOST=0.0.0.0
      - PORT=8081
    command: uvicorn api:app --host 0.0.0.0 --port 8081

  worker_add:
    build:
      context: ./services/add
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc://
    volumes:
      - ./services/add:/worker
    command: celery -A worker worker --loglevel=info -Q queue_add --concurrency=2

  worker_submit:
    build:
      context: ./services/submit
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc://
    volumes:
      - ./services/submit:/worker
      - /data:/data
    command: celery -A worker worker --loglevel=info -Q queue_submit --concurrency=4

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      # - "15672:15672"

  # Optionally, you can also include Flower for monitoring the Celery tasks
  # flower:
  #   image: mher/flower
  #   command: celery --broker=amqp://rabbitmq:5672 flower --port=5555
  #   ports:
  #     - "5556:5555"
  #   depends_on:
  #     - rabbitmq

networks:
  default:
    driver: bridge
